display_errors = on
error_reporting = E_ALL
log_errors = on

post_max_size = 256M
upload_max_filesize = 256M
max_file_uploads = 500

xdebug.mode=off
xdebug.idekey=PHPSTORM
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.start_with_request=yes
xdebug.discover_client_host=true

memory_limit = 512M
